[versions]
commons-codec = "1.19.0"
commons-lang3 = "3.18.0"
commons-math3 = "3.6.1"
commons-text = "1.14.0"
dotenv-java = "3.2.0"
fastutil = "8.5.16"
guava = "33.4.8-jre"
jackson = "2.19.2"
javapoet = "0.7.0"
jetbrains-annotations = "26.0.2"
jgrapht-core = "1.5.2"
jsoup = "1.21.1"
nuprocess = "3.0.0"
ojalgo = "56.1.1"
quarkus-resteasy-problem = "3.21.0"

[libraries]
commons-codec = { group = "commons-codec", name = "commons-codec", version.ref = "commons-codec" }
commons-lang3 = { group = "org.apache.commons", name = "commons-lang3", version.ref = "commons-lang3" }
commons-math3 = { group = "org.apache.commons", name = "commons-math3", version.ref = "commons-math3" }
commons-text = { group = "org.apache.commons", name = "commons-text", version.ref = "commons-text" }
dotenv-java = { group = "io.github.cdimascio", name = "dotenv-java", version.ref = "dotenv-java" }
fastutil = { group = "it.unimi.dsi", name = "fastutil", version.ref = "fastutil" }
guava = { group = "com.google.guava", name = "guava", version.ref = "guava" }
jackson = { group = "com.fasterxml.jackson.core", name = "jackson-databind", version.ref = "jackson" }
jackson-datatype-jsr310 = { group = "com.fasterxml.jackson.datatype", name = "jackson-datatype-jsr310", version.ref = "jackson" }
javapoet = { group = "com.palantir.javapoet", name = "javapoet", version.ref = "javapoet" }
jetbrains-annotations = { group = "org.jetbrains", name = "annotations", version.ref = "jetbrains-annotations" }
jgrapht-core = { group = "org.jgrapht", name = "jgrapht-core", version.ref = "jgrapht-core" }
jsoup = { group = "org.jsoup", name = "jsoup", version.ref = "jsoup" }
nuprocess = { group = "com.zaxxer", name = "nuprocess", version.ref = "nuprocess" }
ojalgo = { group = "org.ojalgo", name = "ojalgo", version.ref = "ojalgo" }
quarkus-resteasy-problem = { group = "io.quarkiverse.resteasy-problem", name = "quarkus-resteasy-problem", version.ref = "quarkus-resteasy-problem" }
